[package]
name = "ldsc_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"
phf = { version = "0.12.1", features = ["macros"] }
polars = "0.49.1"
tempdir = "0.3.7"
